import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NetflixNavHeader from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "INSIGHTS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NetflixNavHeader />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mt-24`}
      >
        {children}
      </body>
    </html>
  );
}
